spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc mysql://sh-cynosdbmysql-grp-98pxrcoqsql:tencentcdb:com:29164/user-center?usessL=false'
    username: username
    password: password
  # session失效时间
  session:
    timeout: 86400